### ISSUE TITLE
Port: armv7

### ISSUE THREAD

**Issue by pr0me** [frida/frida-rust#10]
Hey,

I am trying to cross-compile the gum and gum-sys crates from x64 to armv7-unknown-linux-gnueabihf and running into
multiple build environment failures, wondered if you could point me in the right direction.

This is the error message I am getting:
```
process didn't exit successfully: `/home/target/debug/build/frida-gum-sys-8f9597fdb6792049/build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=event_sink.c
  cargo:rerun-if-changed=event_sink.h
  cargo:rerun-if-changed=invocation_listener.c
  cargo:rerun-if-changed=invocation_listener.h
  cargo:rustc-link-search=/home/pr0me/.cargo/registry/src/frida-gum-sys-0.2.3
  cargo:rustc-link-lib=frida-gum-linux-arm
  cargo:rustc-link-lib=pthread

  --- stderr
  tar: This does not look like a tar archive
  xz: (stdin): File format not recognized
  tar: Child returned status 1
  tar: Error is not recoverable: exiting now
  mv: cannot stat 'libfrida-gum.a': No such file or directory
  ./frida-gum.h:7579:3: error: static_assert failed due to requirement 'sizeof(unsigned long long) == sizeof(unsigned long)' "Expression evaluates to false"
  /usr/include/pthread.h:675:6: error: 'regparm' is not valid on this platform
  /usr/include/pthread.h:687:3: error: 'regparm' is not valid on this platform
  /usr/include/pthread.h:728:6: error: 'regparm' is not valid on this platform
  ./frida-gum.h:7579:3: error: static_assert failed due to requirement 'sizeof(unsigned long long) == sizeof(unsigned long)' "Expression evaluates to false", err: true
  /usr/include/pthread.h:675:6: error: 'regparm' is not valid on this platform, err: true
  /usr/include/pthread.h:687:3: error: 'regparm' is not valid on this platform, err: true
  /usr/include/pthread.h:728:6: error: 'regparm' is not valid on this platform, err: true
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()'
  ```
  
1. I am using the "auto-download" feature, the build script apparently still has problems locating libfrida-gum.a, even after manually downloading the devkit and placing the files in usr/local/{include, lib}.

2. Also the assert fails for some reason. Is this part of bindgen, not being aware of the cc target? I'd assume that rustc
should handle the linking correctly.

3.The build script is trying to link the local pthread.h. How do you handle this on your systems, just by adjusting the build script to look for a local copy of pthread for arm or is there a smoother way?

Any help/heads-up at all is appreciated,
Thanks

**Comment by meme** [comment]
If you clone the repository locally with `auto-download` disabled and replace the `frida-gum.h` and `libfrida-gum.a` in `gum-sys` is it possible to cause this issue?

**Comment by pr0me** [comment]
The build command I used is `cargo build --target armv7-unknown-linux-gnueabihf`.

Apparently it was indeed _bindgen_. I did as you adviced and managed to successfully link against a local copy of the crate/repo after adding `.clang_arg("--sysroot=/usr/arm-linux-gnueabihf")` (or whatever your path for cross libs is) to the bindgen Builder (frida-gum-sys/build.rs:45). 

You can also specify this as an env var:
`BINDGEN_EXTRA_CLANG_ARGS='--sysroot /usr/arm-linux-gnueabihf' cargo build --target armv7-unknown-linux-gnueabihf`. 

Compilation still fails as some stuff is only implemented for x64 and aarch64, but I can work through that :)

Thank you!
