### ISSUE TITLE
Why not support rpc call like golang/python?

### ISSUE THREAD

**Issue by wethura** [frida/frida-rust#105]

**Comment by s1341** [comment]
We haven't needed it yet. Go ahead and send a PR?

**Comment by iteroji** [comment]
I think I'll take a stab at it, but no promises regarding eta

**Comment by charleywright** [comment]
@iteroji Did you make any progress with this? It's currently the only reason I can't use entirely Rust for my Frida experiments. If other stuff has taken priority I'd be happy to give it a look but it might take a while especially if you had some rough ideas or something to start from. Thanks

**Comment by Xoffio** [comment]
I just started to work on this. I have a working prototype. I will create a PR in a couple of days.
