### ISSUE TITLE
backtrace is not supported on Windows. Why?

### ISSUE THREAD

**Issue by r4ve1** [frida/frida-rust#106]
I'm currently working on a project where I need to intercept an ABI and gather backtrace information in pure Rust. I noticed that the `Thread.backtrace` method is not available on Windows platforms due to `frida-gum` disabling the Backtracer-related APIs.

Questions:
1. Is there a specific reason why these APIs are disabled on Windows?
2. Are there any workarounds or alternative methods to accomplish this in pure Rust?
3. Is there anything I can contribute to help enable this feature on Windows?

Thanks for your patience, and btw this is a really cool project!

**Comment by s1341** [comment]
Not sure why we disabled backtrace on windows. Try to disable the disabling and find out?

Also note that frida is the furthest thing from a pure Rust solution...

**Comment by r4ve1** [comment]
closed by #109
