### ISSUE TITLE
use rustls for downloading?

### ISSUE THREAD

**Issue by aviramha** [frida/frida-rust#125]
We have an issue where we don't want to require openssl while building, and Frida doesn't really respect the use of rustls in reqwest if not changing it explicitly in Frida.
I want to suggest to use rustls by default for the build script - it's egoistic but I think rustls is nicer anyway :D

**Comment by s1341** [comment]
I'm willing to consider it... would you be prepared to do a PR?

**Comment by aviramha** [comment]
ofc! It's in my fork already :)

**Comment by aviramha** [comment]
https://github.com/frida/frida-rust/pull/126

**Comment by s1341** [comment]
Thanks!
