### ISSUE TITLE
Rust+JS

### ISSUE THREAD

**Issue by andreafioraldi** [frida/frida-rust#28]
Hi guys,
any idea about how can I expose things written with frida-rust to JS using them alongside the frida-js API?
Linking the gumjs devkit and exposing the bindings should be enough or not?

**Comment by WorksButNotTested** [comment]
Maybe this will help. https://github.com/AFLplusplus/AFLplusplus/tree/dev/frida_mode/src/js

This is how I integrated JS support in AFL++ Frida. By loading for an additional script into the JS runtime, you can add JS bindings to the global namespace too.

See here for how it can be used.

https://github.com/AFLplusplus/AFLplusplus/blob/dev/frida_mode/Scripting.md

**Comment by meme** [comment]
Closing this issue as I believe it's been answered.
