### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by syheliel** [frida/frida-rust#36]
I'm using `gcc` in `msys2` on Windows. I create a new cargo project and add `frida-gum-sys="0.3"` in `[dependencies]`, following is the error.
```
Caused by:
  process didn't exit successfully: `E:\git\gum-test\target\debug\build\frida-gum-sys-050afd60ff0623a6\build-script-build` (exit code: 101)
  --- stdout
  cargo:rustc-link-search=C:\Users\xxx\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\frida-gum-sys-0.3.3
  cargo:rustc-link-lib=frida-gum

  --- stderr
  ./event_sink.h:9:10: fatal error: 'frida-gum.h' file not found
  ./event_sink.h:9:10: fatal error: 'frida-gum.h' file not found, err: true
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', C:\Users\xxx\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\frida-gum-sys-0.3.3\build.rs:63:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  ```
I can find `frida-gum.h` in [frida-gum-devkit](https://github.com/frida/frida/releases/download/15.1.17/frida-gum-devkit-15.1.17-android-arm.tar.xz), but I have no idea where to put the `.lib` and `.h`. I'm new to frida so sorry if I just raise a dummy question.

**Comment by s1341** [comment]
Try setting the `auto-download` feature.

**Comment by s1341** [comment]
no idea. You'll need to figure out why the bindgen is resulting in this error.

**Comment by syheliel** [comment]
It's maybe obvious but I still want to ask: does it currently support `windows`? I find that tests only run on Ubuntu and macOS in GitHub workflow.

**Comment by s1341** [comment]
It hasn't really been tested properly on windows. It's possible something broke. Adding windows support would be a very nice PR.

**Comment by meme** [comment]
Yes, unfortunately Windows support has been a work in progress but noone has dedicated to adding first-class support for it. The first thing to add would be Windows CI, such that we can ensure any future patches do not break the support further.

**Comment by syheliel** [comment]
@meme I have added windows CI in PR #37, but it failed when testing all features, any ideas?

**Comment by meme** [comment]
Seeing that we have Windows CI as of https://github.com/frida/frida-rust/commit/375743f51f79e2c2a72afa9415a0c657b6d7fa2d. I am going to mark this as closed. Please open a new issue if Windows support regresses.
