### ISSUE TITLE
Can you develop a script integration

### ISSUE THREAD

**Issue by InfernalAzazel** [frida/frida-rust#41]
Like python, pip install Frida tool is too comfortable. It's too troublesome to put rust around. I hope it can support rust better

**Comment by meme** [comment]
Hi, can you be more specific in how we can improve the usability of this Rust crate?

**Comment by InfernalAzazel** [comment]
What I'm trying to say is that there can be CLI tools like python
python:

pip install frida-tools # CLI tools
pip install frida       # Python bindings

rust:
cargo install frida-cli

**Comment by InfernalAzazel** [comment]
If frida supports rust like python, combined with tarui, it can also support cross-platform mobile phones quickly, and you can easily make frida apps without any dependencies.

**Comment by meme** [comment]
Please consider using the `auto-download` feature. It is quite straightforward to install Frida for frida-rust.

**Comment by InfernalAzazel** [comment]
> auto-download

Where do I download auto-download can you explain in detail in the documentation? thanks!

**Comment by InfernalAzazel** [comment]
> auto-download

Where do I download auto-download can you explain in detail in the documentation? thanks!
