### ISSUE TITLE
windows build fail

### ISSUE THREAD

**Issue by KnoooW** [frida/frida-rust#43]
Compiling frida-gum-sys v0.3.4 (C:\Users\aaaaaa\Desktop\frida-rust-master_win\frida-gum-sys)
   Compiling reqwest v0.11.10
error: failed to run custom build command for `frida-sys v0.2.3 (C:\Users\aaaaaa\Desktop\frida-rust-master_win\frida-sys)`

Caused by:
  process didn't exit successfully: `C:\Users\aaaaaa\Desktop\frida-rust-master_win\target\debug\build\frida-sys-fb2d4601b8fdea16\build-script-build` (exit code: 101)
  --- stdout
  cargo:rustc-link-search=C:\Users\aaaaaa\Desktop\frida-rust-master_win\frida-sys
  cargo:rustc-link-lib=frida-core

  --- stderr
  C:\Users\aaaaaa\Desktop\frida-rust-master_win\frida-sys/frida-core.h:2748:10: fatal error: 'time.h' file not found
  C:\Users\aaaaaa\Desktop\frida-rust-master_win\frida-sys/frida-core.h:2748:10: fatal error: 'time.h' file not found, err: true
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', frida-sys\build.rs:57:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `frida-gum-sys v0.3.4 (C:\Users\aaaaaa\Desktop\frida-rust-master_win\frida-gum-sys)`

Caused by:
  process didn't exit successfully: `C:\Users\aaaaaa\Desktop\frida-rust-master_win\target\debug\build\frida-gum-sys-77daf7a450c2d1ee\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=event_sink.c
  cargo:rerun-if-changed=event_sink.h
  cargo:rerun-if-changed=invocation_listener.c
  cargo:rerun-if-changed=invocation_listener.h
  cargo:rustc-link-search=C:\Users\aaaaaa\Desktop\frida-rust-master_win\frida-gum-sys
  cargo:rustc-link-lib=frida-gum

  --- stderr
  C:\Users\aaaaaa\Desktop\frida-rust-master_win\frida-gum-sys/frida-gum.h:2812:10: fatal error: 'time.h' file not found
  C:\Users\aaaaaa\Desktop\frida-rust-master_win\frida-gum-sys/frida-gum.h:2812:10: fatal error: 'time.h' file not found, err: true
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', frida-gum-sys\build.rs:63:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

windows x86-64 rust
local build

**Comment by KnoooW** [comment]
add msvc include dir in build.rs fix this error.

**Comment by s1341** [comment]
@KnoooW Do you want to make a PR?

**Comment by KnoooW** [comment]
> 

of course, l will try to make it.
