### ISSUE TITLE
Keeping the original functions

### ISSUE THREAD

**Issue by aviramha** [frida/frida-rust#44]
Hi,
I am wondering if there's a way to keep the original functions that are hooked in some kind of structure so we can call it directly, avoiding relying on the infinite recursion fix that frida provides out of the box.
Our problem is that from our code we get to the hook and then we sometimes have deadlocks.. if we could just call the original functions directly when desired it'd be great!

**Comment by meme** [comment]
Could you share a more concrete example of what you are trying to do, perhaps with a reproducer?

I am also wondering how this relates to https://github.com/frida/frida-rust/issues/38 where how to call the original function from the replacement is described: https://github.com/frida/frida-rust/issues/38

**Comment by aviramha** [comment]
It's not an existing feature so I can't do a reproducer, but I'd wish to call the hooked function directly instead going through the trampoline figuring out we want the original function.

**Comment by oleavr** [comment]
@aviramha It would be easy to add this. We could change:

```
GUM_API GumReplaceReturn gum_interceptor_replace (GumInterceptor * self,
    gpointer function_address, gpointer replacement_function,
    gpointer replacement_data);
```

to:

```
GUM_API GumReplaceReturn gum_interceptor_replace (GumInterceptor * self,
    gpointer function_address, gpointer replacement_function,
    gpointer replacement_data, gpointer * original_function);
```

And just before `goto beach;` [here](https://github.com/frida/frida-gum/blob/696da053d72fcaa52ebf6960997a7c3dfc74f3ba/gum/guminterceptor.c#L538 we would assign [on_invoke_trampoline](https://github.com/frida/frida-gum/blob/696da053d72fcaa52ebf6960997a7c3dfc74f3ba/gum/guminterceptor-priv.h#L46) to the `out`-argument:

```C
  *original_function = function_ctx->on_invoke_trampoline;
```

Would you be interested in cooking up a PR for it? :)

**Comment by aviramha** [comment]
Yeah, given it's a welcome change I'd love to.

**Comment by aviramha** [comment]
@oleavr - I think to make `original_function` nullable and only set it when not NULL. wdyt?

**Comment by oleavr** [comment]
@aviramha Yes, definitely nullable, forgot to say that.

**Comment by aviramha** [comment]
@oleavr Cool! I think I finished the PR - just writing tests. Can you approve workflow to run?

**Comment by aviramha** [comment]
Starting to work on the Rust PR - 
I think of two options to add it:
- Add a new function `replace_return_original` then return the pointer.
- Change the signature, make it an Option - it's less Rusty?

**Comment by meme** [comment]
I don't see why we don't just make `replace` return a `NativePointer` to the original? Right now it returns `()` (a Unit), so we can just instead always return the replacement type.

IMO makes for a much cleaner API than an `Option` or a new function.

**Comment by aviramha** [comment]
@meme yeah that makes sense, don't know why it didn't cross my mind :)
can we merge the gum part?
