### ISSUE TITLE
cargo build fails

### ISSUE THREAD

**Issue by gurkerl83** [frida/frida-rust#58]
I followed the instructions for local development. Unfortunately the build responds with this error

```
./event_sink.h:9:10: fatal error: 'frida-gum.h' file not found
./event_sink.h:9:10: fatal error: 'frida-gum.h' file not found, err: true
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', frida-gum-sys/build.rs:64:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The file frida.gum.h is in the include folder. I do not get whats wrong, can someone provide help?

Thx!

**Comment by meme** [comment]
You can use `cargo build --all-features` which will enable the `auto-download` feature which will download the devkit for you automatically.

Otherwise, you can place `frida-gum.h` and `frida-core.h` in `/usr/local/include` and `libfrida-gum.a` and `libfrida-core.a` in `/usr/local/lib`.

Lastly, for a local installation you can put `frida-gum.h` and `libfrida-gum.a` in the `frida-gum-sys` folder and `frida-core.h` and `libfrida-core.a` in the `frida-core-sys` folder.

Your options are documented here: https://github.com/frida/frida-rust/tree/main/frida-gum#before-installing

**Comment by gurkerl83** [comment]
@meme Thx for answering. I followed the instructions. In the past it was working, I played a few month back with frida-rust. Unfortunately I can not get the local dev installation to work.

Putting the files in usr/local/include respectively usr/local/lib I get an error that time.h is missing.

```
/usr/local/include/frida-gum.h:2782:10: fatal error: 'time.h' file not found
/usr/local/include/frida-gum.h:2782:10: fatal error: 'time.h' file not found, err: true
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', frida-gum-sys/build.rs:64:10
```

```
/usr/local/include/frida-core.h:2763:10: fatal error: 'time.h' file not found
/usr/local/include/frida-core.h:2763:10: fatal error: 'time.h' file not found, err: true
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', frida-sys/build.rs:58:10
```
I try to compile this on MacOs, also using the latest rust version.

Thx!

**Comment by meme** [comment]
This is macOS? What version? Do you have XCode installed?

**Comment by gurkerl83** [comment]
Sry, yes macOS, also the latest XCode version (13.4.1)

**Comment by meme** [comment]
Can you run `xcode-select --install` again? The only thing I can think of is that you do not have the macOS SDK headers installed

**Comment by gurkerl83** [comment]
Working now, but the re-installation did not solve the problem. The c-headers where missing in usr/local/include.

This stack-overflow discussion helped a lot.
https://stackoverflow.com/questions/58278260/cant-compile-a-c-program-on-a-mac-after-upgrading-to-catalina-10-15/58349403#58349403

Creating symlinks for those header files solved the problem.

```
ln -s /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/* /usr/local/include/
```

Thanks for your effort!
