### ISSUE TITLE
 Can't use `frida-gum` crate on arm64 linux (docker container on Mac with apple chip)

### ISSUE THREAD

**Issue by t4lz** [frida/frida-rust#66]
Trying to build a project with `frida-gum` as a dependency, the build fails with the following error:

```
error[E0432]: unresolved import `_frida_g_object_unref`
  --> /root/.cargo/git/checkouts/frida-rust-573843e2226aec3c/3d9308a/frida-gum-sys/src/lib.rs:25:9
   |
25 | pub use _frida_g_object_unref as g_object_unref;
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no external crate `_frida_g_object_unref`
```

This happens both with or without `auto-download`.

I tried to understand why this happens, but I'm not sure yet so I also made [a repo](https://github.com/t4lz/use-frida) to help people reproduce it.
On a Mac with an apple chip, you reproduce it with:
```
git clone git@github.com:t4lz/use-frida.git && cd use-frida && docker build -t rust-use-frida . && docker run -t rust-use-frida
```
or 
```
git clone -b manually git@github.com:t4lz/use-frida.git && cd use-frida && docker build -t rust-use-frida . && docker run -t rust-use-frida
```
for a version without `auto-download`.

If I have time I'll try to find a fix, but I'm new to Frida and to its codebase.

**Comment by WorksButNotTested** [comment]
I'm encountering this issue too, but it looks like the fix was subsequently backed out?
https://github.com/frida/frida-rust/commit/4c5b732416f6c9cbff40413be4cc20d921a75953

Do you have any updated advice on how to address it?

**Comment by meme** [comment]
It was backed out because it is no longer required on Frida 16 reportedly: https://github.com/frida/frida-rust/pull/68. Are you using the latest Frida and latest Frida Rust? It is possible it has regressed.

**Comment by WorksButNotTested** [comment]
Thanks. I thought I had already bumped the version, but it seems cargo needed a bit more convincing! It’s working ok for me with the latest now thanks.
