### ISSUE TITLE
Autodownload Feature for Windows

### ISSUE THREAD

**Issue by domenukk** [frida/frida-rust#9]
The autodownload feature uses `wget` and `tar`, both could eventually be replaced with rust features.
This would allow Windows (and obscure other systems) to auto-download too, even if gnu tools are not present.

For example wget could be replaced with `reqwest`:
https://rust-lang-nursery.github.io/rust-cookbook/web/clients/download.html
tar with this:
https://rust-lang-nursery.github.io/rust-cookbook/compression/tar.html

**Comment by meme** [comment]
@s1341 are you interested in working on this? Would be good to have SHA256 integrity checks as well.

**Comment by domenukk** [comment]
Looked into it myself and actually on window the devkit comes as self unpacking .exe file, so some more work for adaption and testing is needed. Out of time for today

**Comment by s1341** [comment]
@domenukk I'm certain that @oleavr would be happy to provide a tarball too, if we ask him.

**Comment by s1341** [comment]
@oleavr says that he is happy to accept PRs against releng/release.py.

It shouldn't be too difficult to do.

**Comment by meme** [comment]
https://github.com/frida/frida-rust/commit/6c8d2872bc203c7a4df0818bbee146c7ec9dc80a
