### ISSUE TITLE
Can't cross-compile for `x86_64-pc-windows-gnu` target

### ISSUE THREAD

**Issue by dzervas** [frida/frida-rust#95]
When I `cargo build --bins --target x86_64-pc-windows-gnu` I get:

```
   Compiling frida-sys v0.4.0
   Compiling frida v0.4.0
error: could not find native static library `frida-core`, perhaps an -L flag is missing?

The following warnings were emitted during compilation:

warning: Frida core devkit not found, downloading from https://github.com/frida/frida/releases/download/16.0.7/frida-core-devkit-16.0.7-windows-x86_64.tar.xz...

error: could not compile `frida-sys` due to previous error
```

Compiling the same code for linux (the default target) I don't have that problem - my code is portable so that ain't a problem
I've got the `auto-download` feature enabled for both `frida` and `frida-sys` (using the upstream `0.4.0` versions)

**Comment by s1341** [comment]
Frida doesn’t currently provide a devkit compatible with that toolchain. I’ve started working on this but it’s not yet ready.

**Comment by dzervas** [comment]
Oh and I guess [cargo-xwin](https://github.com/rust-cross/cargo-xwin) is not an option since `frida-sys` requires `pthread.lib` and `resolv.lib` (maybe they're available through wine somehow?)
